chatgpt:
  email: "email@gmail.com"
  password: "password"
  access_token: "<access_token>"
  version: "v1"

plugins:
  wp_louis_ck:
    base_url: "https://localhost:8080/"
    username: "wordpress"
    password: "wordpress"
